### ISSUE TITLE
No build for Linux.

### ISSUE THREAD

**Issue by coolboy19521** [toghrul-guluzade/Christmas-Tree#1]
You have shared .exe file (a windows build) in your repo. But not one for Linux? Are you racist? Nor for Linux, neither for Mac. Interesting.

**Comment by toghrul-guluzade** [comment]
Hey there! I mainly use Windows, and I apologize for any inconvenience. I'll try to solve it as soon as possible

**Comment by coolboy19521** [comment]
> Hey there! I mainly use Windows, and I apologize for any inconvenience. I'll try to solve it as soon as possible

You're a newbie. Not a problem for this time. Happy coming St. Joseph's day btw.

**Comment by coolboy19521** [comment]
I close the issue.
